apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- api-deployment.yaml
- worker-deployment.yaml
- service.yaml
images:
- name: 858507113889.dkr.ecr.ap-northeast-2.amazonaws.com/aims/ai-service
  newName: 858507113889.dkr.ecr.ap-northeast-2.amazonaws.com/aims/ai-service
  newTag: dev-9ad0be28c539
