apiVersion: v1
kind: Service
metadata:
  name: ai-service-api
  namespace: aims-project
  labels:
    app: ai-service-api
spec:
  type: ClusterIP
  selector:
    app: ai-service-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
