apiVersion: v1
kind: ServiceAccount
metadata:
  name: assembly-service
  namespace: aims-project
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::858507113889:role/aims-dev-assembly-service-role
