apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: aims-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081

          envFrom:
            - secretRef:
                name: backend-rds-secret

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev

            - name: SERVER_PORT
              value: "8081"

            - name: MANAGEMENT_HEALTH_REDIS_ENABLED
              value: "false"

            - name: SPRING_CACHE_TYPE
              value: "none"

          readinessProbe:
            httpGet:
              path: /api/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /api/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: aims-project
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 8081
      targetPort: 8081