apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: aims-project
data:
  APP_NAME: backend
  SPRING_PROFILES_ACTIVE: dev
  SERVER_PORT: "8081"
  MANAGEMENT_HEALTH_REDIS_ENABLED: "true"
  SPRING_CACHE_TYPE: none
  REDIS_TIMEOUT: 3s
  REDIS_CACHE_TTL: 10m

  OPENSEARCH_SCHEME: http
  OPENSEARCH_HOST: elasticsearch.platform.svc.cluster.local
  OPENSEARCH_PORT: "9200"