input {
  kafka {
    id => "aims-msk-input"

    bootstrap_servers => "${MSK_BOOTSTRAP_SERVERS}"

    topics => [
      "factory.manufacturing.raw",
      "factory.manufacturing.analysis",
      "factory.manufacturing.alert",
      "factory.equipment.status",
      "quality.inspection.process",
      "quality.inspection.summary",
      "quality.inspection.status_detail",
      "quality.inspection.drive_detail",
      "quality.inspection.risk_history",
      "quality.inspection.risk_trend"
    ]

    group_id => "aims-logstash-dev"
    client_id => "aims-logstash"

    security_protocol => "SASL_SSL"
    sasl_mechanism => "AWS_MSK_IAM"
    sasl_jaas_config => "software.amazon.msk.auth.iam.IAMLoginModule required;"
    sasl_client_callback_handler_class => "software.amazon.msk.auth.iam.IAMClientCallbackHandler"

    auto_offset_reset => "earliest"
    enable_auto_commit => true
    decorate_events => "basic"
    codec => plain
  }
}

filter {
  mutate {
    add_field => {
      "kafka_topic" => "%{[@metadata][kafka][topic]}"
      "kafka_partition" => "%{[@metadata][kafka][partition]}"
      "kafka_offset" => "%{[@metadata][kafka][offset]}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch.platform.svc.cluster.local:9200"]
    index => "aims-%{[kafka_topic]}-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
