apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend-ingress.yaml
  - backend-ingress.yaml
  - assembly-service-ingress.yaml
  - quality-service-ingress.yaml
  - ai-service-ingress.yaml
