apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quality-service-ingress
  namespace: aims-project
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: aims-dev-alb
    alb.ingress.kubernetes.io/group.name: aims-dev-app
    alb.ingress.kubernetes.io/group.order: '30'

    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/security-groups: ALB_SECURITY_GROUPS_PLACEHOLDER

    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: CERTIFICATE_ARN_PLACEHOLDER
    alb.ingress.kubernetes.io/ssl-redirect: '443'

    alb.ingress.kubernetes.io/healthcheck-path: /api/quality/health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: '200'
spec:
  ingressClassName: alb
  rules:
    - host: aims-factory.com
      http:
        paths:
          - path: /api/quality
            pathType: Prefix
            backend:
              service:
                name: quality-service
                port:
                  number: 8083