apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aims-assembly-service-dev
  namespace: platform

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/SK-Rookies-AIMS/infra.git
    targetRevision: dev
    path: k8s/assembly-service

  destination:
    server: https://kubernetes.default.svc
    namespace: aims-project

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ApplyOutOfSyncOnly=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m