apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aims-ingress-dev
  namespace: platform
spec:
  project: default

  source:
    repoURL: https://github.com/SK-Rookies-AIMS/infra.git
    targetRevision: dev
    path: k8s/ingress

  destination:
    server: https://kubernetes.default.svc
    namespace: aims-project

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
